{
 "title": "3D Printers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values({job=\"klipper\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(klipper_system_cpu, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Print Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Print Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_print_gcode_progress{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Total Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_print_total_duration{job=\"$job\", instance=\"$instance\"} / 60 / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filament Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_print_filament_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Estimated Print Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_toolhead_estimated_print_time{job=\"$job\", instance=\"$instance\"} / 60 / 60",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Toolhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Pressure Advance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "PA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_extruder_pressure_advance{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_gcode_speed_factor{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_gcode_extrude_factor{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Accel" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_gcode_speed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Thermals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Hotend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_extruder_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hotend Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_extruder_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extruder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_extruder_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_extruder_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_extruder_target{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_fan_speed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Bed Heater",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_heater_bed_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed Heater Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_heater_bed_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heated Bed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_heater_bed_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_heater_bed_target{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_heater_bed_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Enclosure Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_temperature_sensor_temperature{job=\"$job\", instance=\"$instance\", sensor=\"chamber\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Enclosure Temp 24h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(klipper_temperature_sensor_temperature{job=\"$job\", instance=\"$instance\", sensor=\"chamber\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enclosure Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_temperature_sensor_temperature{job=\"$job\", instance=\"$instance\", sensor=\"chamber\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_time{job=\"$job\", instance=\"$instance\"} / 60 / 60",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Longest Print",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_longest_print{job=\"$job\", instance=\"$instance\"} / 60 / 60",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_jobs{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Filament Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_filament_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Klipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_cpu_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "klipper_system_cpu{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_system_cpu_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_moonraker_cpu_usage{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "klipper_system_memory_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_system_memory_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_memory_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Klipper Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "{job=\"$job\", instance=\"$instance\", filename=\"/klipper/logs/klippy.log\"} |= `error`"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 7, "x": 13, "y": 50 } },
  {
   "title": "CAN BUS",
   "type": "logs",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 50 },
   "targets": [
    {
     "expr": "{job=\"$job\", instance=\"$instance\", filename=\"/klipper/logs/klippy.log\"} |= `canbus`"
    }
   ]
  },
  { "title": "MCU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "MCU Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_temperature_sensor_temperature{job=\"$job\", instance=\"$instance\", sensor=\"MCU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU CPU Frequency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_mcu_clock_frequency{job=\"$job\", instance=\"$instance\", mcu=\"mcu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "klipper_mcu_read_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_mcu_ready_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_mcu_receive_seq{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MCU Invalid/Stalled Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "klipper_mcu_invalid_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_mcu_stalled_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_mcu_retransmit_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_mcu_retransmit_seq{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(klipper_network_rx_bytes{job=\"$job\", instance=\"$instance\", interface!=\"lo\", interface=\"wlan0\"}[$__rate_interval])",
     "legendFormat": " {{interface}} rx_bytes"
    },
    {
     "expr": "rate(klipper_network_tx_bytes{job=\"$job\", instance=\"$instance\", interface!=\"lo\", interface=\"wlan0\"}[$__rate_interval])",
     "legendFormat": "{{interface}} tx_bytes "
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(klipper_network_rx_drop{job=\"$job\", instance=\"$instance\", interface!=\"lo\", interface=\"wlan0\"}[$__rate_interval])",
     "legendFormat": " {{interface}} rx_drop"
    },
    {
     "expr": "rate(klipper_network_tx_drop{job=\"$job\", instance=\"$instance\", interface!=\"lo\", interface=\"wlan0\"}[$__rate_interval])",
     "legendFormat": "{{interface}} tx_drop"
    }
   ]
  }
 ]
}